// <auto-generated />
using Dreamlines.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dreamlines.DAL.Migrations
{
    [DbContext(typeof(SalesunitContext))]
    [Migration("20191215123342_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dreamlines.DAL.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookingDate");

                    b.Property<int>("Price");

                    b.Property<int>("ShipId");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Dreamlines.DAL.Salesunit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Currency");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Salesunits");
                });

            modelBuilder.Entity("Dreamlines.DAL.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("SalesunitId");

                    b.HasKey("Id");

                    b.HasIndex("SalesunitId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("Dreamlines.DAL.Booking", b =>
                {
                    b.HasOne("Dreamlines.DAL.Ship")
                        .WithMany("Bookings")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dreamlines.DAL.Ship", b =>
                {
                    b.HasOne("Dreamlines.DAL.Salesunit")
                        .WithMany("Ships")
                        .HasForeignKey("SalesunitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
